services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paytoll
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3000:3000"  # Exposes the app on localhost:3000
    restart: unless-stopped